### 
GET http://localhost:3000/api/hello


### REGISTER USER
POST http://localhost:3000/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Giandev",
  "username": "gian123",
  "email": "gian123@gmail.com",
  "password": "123456"
}

### LOGIN USER
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "superadmin",
  "password": "123456"
}


### LOGOUT USER
POST http://localhost:3000/api/auth/logout
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6MSwidXNlcm5hbWUiOiJzdXBlcmFkbWluIiwiZW1haWwiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczNzcwMDc5NywiZXhwIjoxNzM3NzA0Mzk3fQ.8DPVAWsKPIOVCaBWT4Xxzfq3rE5QknWYvsujEgiv0Cg


### GET LIST USER
GET http://localhost:3000/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6MSwidXNlcm5hbWUiOiJzdXBlcmFkbWluIiwiZW1haWwiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczNzcwMDc5NywiZXhwIjoxNzM3NzA0Mzk3fQ.8DPVAWsKPIOVCaBWT4Xxzfq3rE5QknWYvsujEgiv0Cg

### CREATE USER
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6MSwidXNlcm5hbWUiOiJzdXBlcmFkbWluIiwiZW1haWwiOiJzdXBlcmFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczNzcwMDc5NywiZXhwIjoxNzM3NzA0Mzk3fQ.8DPVAWsKPIOVCaBWT4Xxzfq3rE5QknWYvsujEgiv0Cg

{
  "name": "Arhan",
  "username": "arhan",
  "email": "arhan@gmail.com",
  "password": "123456"
}

### UPDATE USER
PUT http://localhost:3000/api/users/2
Content-Type: application/json
Accept: application/json

{
  "name": "Arhan update",
  "username": "arhan",
  "email": "arhan@gmail.com",
  "password": "123456"
}

### FIND USER BY ID
GET http://localhost:3000/api/users/1
Accept: application/json

### DELETE USER
DELETE http://localhost:3000/api/users/1
Accept: application/json